name: Windows Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Check docker buildx version
      shell: cmd
      run: export DOCKER_CLI_EXPERIMENTAL=enabled
      
    - name: Check docker buildx version
      shell: cmd
      run: docker buildx version
        
    - name: Build image
      shell: bash
      run: |
        ./makeimage.sh win64 nonfree
        
    - name: Build FFmpeg
      shell: bash
      run: |
        ./build.sh win64 nonfree
