name: Windows Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: msys2/setup-msys2@v2
      with:
        install: >-
          docker-buildx-plugin
        path-type: inherit
        update: true

    - name: Setup MSYS2
      shell: msys2 {0}
      run: docker buildx install
        
    - name: Build image
      shell: bash
      run: |
        ./makeimage.sh win64 nonfree
        
    - name: Build FFmpeg
      shell: bash
      run: |
        ./build.sh win64 nonfree
